### ISSUE TITLE
Merged with yolov8-pose

### ISSUE THREAD

**Issue by lbq779660843** [spacewalk01/yolov9-bytetrack-trt#5]
Hi, nice to meet you again😀.
I've merged this rep with yolov8-pose. So, could I commit my code there?
![1](https://github.com/user-attachments/assets/6d6801fc-884b-4723-aa1f-a0e8ed5f2bd9)
![2](https://github.com/user-attachments/assets/a227f9b0-1928-4b5f-8b1d-d0a223f75531)
![3](https://github.com/user-attachments/assets/74c0acb5-36b6-46bd-ba78-3146d3bc427e)

**Comment by spacewalk01** [comment]
Yes sure

**Comment by spacewalk01** [comment]
And you can change this code and apply your simplified version like you did in depth anything.

**Comment by lbq779660843** [comment]
Can I add your social media contact information？ So we can get in touch more easily.
